openapi: "3.0.0"
info:
  title: learn express and swagger
  description: A Course Segment about writing Docs
  version: 1.1.0
  contact:
    email: yash@gmail.com
    url: "https://yash.com"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for local host - secure or production
#   - url: "http://localhost:4000/api/v1"
#     description: for local host - regular or staging

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host - secure or production
    variables:
      version: # Can be named anything, it is a variable
        enum:
          - v1
          - v2
      protocol: # Can be named anything, it is a variable
        enum:
          - http
          - https


components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer  
